name: android_tutorial
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sensors_plus: ^0.6.0
  http: ^0.12.2
  sqflite: ^1.3.2+4
  shared_preferences: ^0.5.12+4
  provider: ^4.3.3
  webview_flutter: ^1.0.7
  url_launcher: ^5.7.10
  device_apps: ^1.3.0
  android_intent: ^0.3.7+7
  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  rename: ^1.3.1

  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
